### PR TITLE
Add new fixtures and update existing ones

### PR DESCRIPTION
**Pull request by henrist**

### CODE REVIEW

**Comment by matsasc** [comment]
How does fixtures work anyways? will it run i production also?

**Comment by thor** [comment]
@matsasc just dumping this here after reading it and finding it interesting:
https://docs.djangoproject.com/en/1.9/howto/initial-data/

**Comment by henrist** [comment]
> matsasc commented 2 minutes ago
> How does fixtures work anyways? will it run i production also?

Fixtures is loaded when setting up development server (the `scripts/setup_dev.sh`-file we've made). It is also loaded in some of the tests. It will not be loaded in production.

**Comment by henrist** [comment]
Oh, and when running tests, it will set up a test database that will be destroyed after tests are run.

**Pull request merged**
